# Generated by Django 4.2.1 on 2023-05-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text_preview', models.TextField(verbose_name='Textpreview')),
                ('text', models.TextField(verbose_name='Текст статі')),
                ('created_at', models.DateTimeField(verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(verbose_name='Дата зміни')),
            ],
            options={
                'verbose_name': 'Стаття',
                'verbose_name_plural': 'Cтатті',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
            ],
        ),
    ]
